Repository WillStrohl/dnnextensions, pull requests merged in 2024-10, with the labels that each got.

#250 Removed deprecated DLL & updated DNN references to 9.11.00
  Modules/WillStrohl.LightboxGallery/WillStrohl.Modules.Lightbox.vbproj
  Modules/WillStrohl.LightboxGallery/packages.config
Labels: enhancement

#252 Cache bug
  Build/ModulePackage.targets
  Modules/WillStrohl.OpenGraph/WillStrohl.Modules.OpenGraph.vbproj
  Modules/WillStrohl.OpenGraph/WillStrohl.OpenGraph.dnn
  Modules/WillStrohl.OpenGraph/packages.config
Labels: bug

#255 Tasks/release ogp 2.1.0
  Modules/WillStrohl.OpenGraph/My Project/AssemblyInfo.vb
  Modules/WillStrohl.OpenGraph/WillStrohl.Modules.OpenGraph.vbproj
  Modules/WillStrohl.OpenGraph/WillStrohl.OpenGraph.dnn
  Modules/WillStrohl.OpenGraph/WillStrohl.OpenGraph_Symbols.dnn
  Modules/WillStrohl.OpenGraph/packages.config
  Modules/WillStrohl.OpenGraph/releasenotes.txt
Labels: Task

#256 Sync dev and main
  Modules/WillStrohl.OpenGraph/My Project/AssemblyInfo.vb
  Modules/WillStrohl.OpenGraph/WillStrohl.Modules.OpenGraph.vbproj
  Modules/WillStrohl.OpenGraph/WillStrohl.OpenGraph.dnn
  Modules/WillStrohl.OpenGraph/WillStrohl.OpenGraph_Symbols.dnn
  Modules/WillStrohl.OpenGraph/packages.config
  Modules/WillStrohl.OpenGraph/releasenotes.txt
Labels: Task

#258 Lightbox gallery title bug
  Modules/WillStrohl.LightboxGallery/EditLightbox.ascx
  Modules/WillStrohl.LightboxGallery/ViewLightbox.ascx.vb
  Modules/WillStrohl.LightboxGallery/WillStrohl.Modules.Lightbox.vbproj
Labels: bug

#259 Updates for the Lightbox Gallery 1.16.0 release
  Modules/WillStrohl.LightboxGallery/My Project/AssemblyInfo.vb
  Modules/WillStrohl.LightboxGallery/WillStrohl.Lightbox.dnn
  Modules/WillStrohl.LightboxGallery/WillStrohl.Lightbox_Symbols.dnn
  Modules/WillStrohl.LightboxGallery/releasenotes.txt
  Modules/WillStrohl.OpenGraph/releasenotes.txt
Labels: Task

#260 Sync dev and main
  Modules/WillStrohl.LightboxGallery/EditLightbox.ascx
  Modules/WillStrohl.LightboxGallery/My Project/AssemblyInfo.vb
  Modules/WillStrohl.LightboxGallery/ViewLightbox.ascx.vb
  Modules/WillStrohl.LightboxGallery/WillStrohl.Lightbox.dnn
  Modules/WillStrohl.LightboxGallery/WillStrohl.Lightbox_Symbols.dnn
  Modules/WillStrohl.LightboxGallery/WillStrohl.Modules.Lightbox.vbproj
  Modules/WillStrohl.LightboxGallery/releasenotes.txt
  Modules/WillStrohl.OpenGraph/releasenotes.txt
Labels: Task
